spring:
  application:
    name: Web Shared Folder
    version: 0.0.1-SNAPSHOT
    licence: GPLv3
    url: https://github.com/fromiva/WebSharedFolder
  profiles:
    default: production
  datasource:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
  jpa:
    database-platform: org.hibernate.dialect.HSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false
  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:db/changelog/changelog-main.yaml
    contexts: ${spring.profiles.active}
