spring:
  datasource:
    url: jdbc:hsqldb:file:data/data-dev
    username: sa
    password:
  jpa:
    show-sql: true
  liquibase:
    drop-first: true

logging:
  level:
    root: info
    sql: info
    web: info
    org.hibernate: info
    com.github.fromiva: trace
