spring:
  datasource:
    url: jdbc:hsqldb:mem:data;DB_CLOSE_DELAY=-1
    username: sa
    password:
  jpa:
    show-sql: true
  test:
    database:
      replace: none

logging:
  level:
    root: info
    com.github.fromiva: debug
