wsf:
  application:
    name: Web Shared Folder
    version: 0.0.1-SNAPSHOT
    license: GPLv3
    url: https://github.com/fromiva/WebSharedFolder
    settings:
      filesystem:
        sorting: pathByTypeAscComparator, pathByNameAscComparator
    security:
      registration-confirm: true
spring:
  application:
    name: ${wsf.application.name}
  profiles:
    default: production
  datasource:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
  jpa:
    database-platform: org.hibernate.dialect.HSQLDialect
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: false
  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:db/changelog/changelog-main.yaml
    contexts: ${spring.profiles.active}
  servlet:
    multipart:
      enabled: true
      max-file-size: 2GB
      max-request-size: 10GB
management:
  endpoints:
    web:
      exposure:
        include: shutdown
  endpoint:
    shutdown:
      enabled: true
