spring:
  datasource:
    url: jdbc:hsqldb:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
  jpa:
    show-sql: true
  liquibase:
    drop-first: false
    contexts: test

logging:
  level:
    root: debug
